In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('mpg')

In [3]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
df.drop('name',axis=1, inplace=True)

In [5]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [7]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [8]:
#since we have not done outlier treatement, then better idea would be replace the misssing value with median

df['horsepower'].median()

np.float64(93.5)

In [9]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())

In [10]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [12]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [13]:
#data encoding

In [14]:
df['origin'] = df['origin'].map({'usa':1, 'japan':2, 'europe':3})

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(4), int64(4)
memory usage: 25.0 KB

In [16]:
#separate into X and Y

In [17]:
x = df.drop('mpg', axis=1)
y = df['mpg']

In [18]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [19]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [20]:
#train test split

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1)

In [22]:
x_train

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
350,4,105.0,63.0,2215,14.9,81,1
59,4,97.0,54.0,2254,23.5,72,3
120,4,121.0,112.0,2868,15.5,73,3
12,8,400.0,150.0,3761,9.5,70,1
349,4,91.0,68.0,1985,16.0,81,2
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
255,4,140.0,88.0,2720,15.4,78,1
72,8,304.0,150.0,3892,12.5,72,1
235,4,97.0,75.0,2265,18.2,77,2
37,6,232.0,100.0,3288,15.5,71,1

In [23]:
x_test

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
174,6,171.0,97.0,2984,14.5,75,1
359,4,141.0,80.0,3230,20.4,81,3
250,8,318.0,140.0,3735,13.2,78,1
274,5,131.0,103.0,2830,15.9,78,3
283,6,232.0,90.0,3265,18.2,79,1
...,...,...,...,...,...,...,...
382,4,108.0,70.0,2245,16.9,82,2
39,8,400.0,175.0,4464,11.5,71,1
171,4,134.0,96.0,2702,13.5,75,2
271,4,156.0,105.0,2745,16.7,78,1
247,4,85.0,70.0,2070,18.6,78,2

In [24]:
#SLR
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()

In [25]:
regression_model

LinearRegression()

In [26]:
regression_model.fit(x_train,y_train)

LinearRegression()

In [27]:
regression_model.coef_

array([-0.31761423,  0.02623748, -0.01827076, -0.00748775,  0.05040673,
        0.84709514,  1.51909584])

In [28]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {regression_model.coef_[i]}")

The coefficient for cylinders is -0.3176142302799369
The coefficient for displacement is 0.026237482599078946
The coefficient for horsepower is -0.018270764913124595
The coefficient for weight is -0.007487750398361897
The coefficient for acceleration is 0.0504067346197138
The coefficient for model_year is 0.8470951427061365
The coefficient for origin is 1.5190958387975024

In [29]:
#observation 
#coefficient are relatively smaller, if one independent variable changes
#There will be not much difference in prediction
#This is sometime called as smoother model

#these features might might not be contributing in model training

In [30]:
from sklearn.metrics import r2_score

y_pred_linear = regression_model.predict(x_test)
r2_linear = r2_score(y_test,y_pred_linear)
print(f"The r square of Linear regression {r2_linear}")

The r square of Linear regression 0.8348001123742285

In [31]:
#regularization
# ridge regression

In [32]:
from sklearn.linear_model import Ridge
ridge_regression_model = Ridge(alpha=0.1)


#in practical implementation Lambda is alpha

In [33]:
ridge_regression_model

Ridge(alpha=0.1)

In [34]:
ridge_regression_model.fit(x_train,y_train)

Ridge(alpha=0.1)

In [35]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficient for cylinders is -0.317003210100688
The coefficient for displacement is 0.026213249757983868
The coefficient for horsepower is -0.018263252481448933
The coefficient for weight is -0.007487326050213144
The coefficient for acceleration is 0.05036896947442996
The coefficient for model_year is 0.8470062938903175
The coefficient for origin is 1.5174528285653952

In [36]:
#for ridge regression evaluation
y_pred_ridge = ridge_regression_model.predict(x_test)
r2_ridge = r2_score(y_test,y_pred_ridge)
print(f"The r square of Ridge regression {r2_ridge}")

The r square of Ridge regression 0.8348084889168356

In [37]:
#we don't see much variation in coeff of ridge regression with compare to the linear regression

In [38]:
from sklearn.linear_model import Lasso

In [39]:
lasso_regression_model = Lasso(alpha=0.5)

In [40]:
lasso_regression_model

Lasso(alpha=0.5)

In [41]:
lasso_regression_model.fit(x_train,y_train)

Lasso(alpha=0.5)

In [42]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {lasso_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.006208198888300358
The coefficient for horsepower is -0.011058382987169565
The coefficient for weight is -0.0069826731680230885
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.744654952003819
The coefficient for origin is 0.0

In [43]:
#three features coeff is 0, Lasso helps in feature selection

In [44]:
y_pred_lasso = lasso_regression_model.predict(x_test)
r2_lasso = r2_score(y_test,y_pred_lasso)
print(f"The r square of Lasso regression {r2_lasso}")

The r square of Lasso regression 0.8277934716635555

In [45]:
#Elastic net

from sklearn.linear_model import ElasticNet
elastic_net_model = ElasticNet(alpha=1, l1_ratio=0.5)

In [46]:
elastic_net_model

ElasticNet(alpha=1)

In [47]:
elastic_net_model.fit(x_train,y_train)

ElasticNet(alpha=1)

In [48]:
for i, col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {elastic_net_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.005888869953667563
The coefficient for horsepower is -0.012403874933570126
The coefficient for weight is -0.006934550516257631
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7133150744603874
The coefficient for origin is 0.0

In [49]:
y_pred_elastic = elastic_net_model.predict(x_test)
r2_elastic = r2_score(y_test,y_pred_elastic)
print(f"The r square of Elastic regression {r2_elastic}")

The r square of Elastic regression 0.8284840073256804

In [50]:
#Regularization with cross validation
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(cv=5, verbose=2)

In [51]:
lasso_cv

LassoCV(cv=5, verbose=2)

In [52]:
lasso_cv.fit(x_train,y_train)

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

LassoCV(cv=5, verbose=2)

In [53]:
y_pred_lassocv = lasso_cv.predict(x_test)
r2_lassocv = r2_score(y_test,y_pred_lassocv)
print(f"The r square of LassoCV regression {r2_lassocv}")

The r square of LassoCV regression 0.8082805983844751

In [54]:
from sklearn.linear_model import RidgeCV
ridge_cv = LassoCV(cv=5, verbose=2)

In [55]:
ridge_cv.fit(x_train,y_train)

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

LassoCV(cv=5, verbose=2)

In [56]:
y_pred_ridgecv = ridge_cv.predict(x_test)
r2_ridgecv = r2_score(y_test,y_pred_ridgecv)
print(f"The r square of RidgeCv regression {r2_ridgecv}")

The r square of RidgeCv regression 0.8082805983844751

In [57]:
ridge_cv.get_params()

{'alphas': 'warn',
 'copy_X': True,
 'cv': 5,
 'eps': 0.001,
 'fit_intercept': True,
 'max_iter': 1000,
 'n_alphas': 'deprecated',
 'n_jobs': None,
 'positive': False,
 'precompute': 'auto',
 'random_state': None,
 'selection': 'cyclic',
 'tol': 0.0001,
 'verbose': 2}

In [58]:
from sklearn.linear_model import ElasticNetCV

In [59]:
elastic_cv = ElasticNetCV(cv=5)
elastic_cv.fit(x_train,y_train)

ElasticNetCV(cv=5)

In [60]:
y_pred_elastic_cv = elastic_cv.predict(x_test)

In [61]:
y_pred_elastic_cv

array([23.32225361, 23.36845994, 18.14450551, 24.93625853, 22.42286784,
       13.78884339, 31.1671185 , 31.48981601, 16.57604898, 11.28035886,
       28.15675955, 16.37653903, 20.6939379 , 26.11251247, 33.50819798,
       23.61366501, 11.2525497 , 22.33195185,  7.90530825, 31.19454231,
       26.26049817, 31.03501847, 25.00039182, 28.27994041, 24.45115446,
       30.6440601 , 29.27092218, 31.4383626 , 18.26455856, 27.59990746,
       24.89273354, 10.75413097, 22.91899882, 26.84700001, 25.54792583,
       13.98880471, 28.72560255,  7.40991527, 29.66736857, 26.42271906,
       28.66817972, 25.44345873, 18.64230915, 30.34252443, 25.75672281,
       21.18310924, 20.11179682, 12.79982325, 29.12674599, 18.89086269,
       28.05803233, 25.51554452, 15.47728843, 12.55914918, 30.0594323 ,
       27.3938317 ,  9.60281401, 13.96198918, 30.63798644, 32.18001152,
       31.94368422, 32.18001152, 16.89612729, 26.12420993, 16.79988196,
       30.39498847, 26.44634867, 24.28205985, 28.16472676, 13.56216155,
       16.92175707, 26.77009214, 16.82207274, 26.62378361, 14.0444144 ,
       29.21435706, 25.23514515, 15.17474439, 11.24774813, 26.91027406,
       17.51250216, 18.9932598 , 31.76836608, 27.88006137, 31.29497633,
       17.65240567, 14.43723626, 22.56219236, 32.61432032, 29.15130215,
       16.20124433, 23.52829523, 21.44104833, 23.34552006, 30.98079948,
       24.04198807, 30.54763903, 28.86290841, 25.84986392, 21.64837588,
       20.89654694, 10.88968574, 16.58337958, 31.84161992, 14.61628151,
       21.16311349, 30.65805834, 24.83080824, 23.89427753, 17.00667093,
       20.8112802 , 28.1869392 , 28.19008257, 18.03947533, 25.68439592,
       30.27032371, 11.10144741, 25.23106539, 25.43296096, 30.55637337])

CV with Hyperparameter tuning

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import Lasso, Ridge

In [ ]:
#grid search CV for Lasso
lasso = Lasso()
lasso

Lasso()

In [66]:

param_grid = {'alpha': [0.001, 0.1, 0.01, 1,10, 100]}
param_grid

{'alpha': [0.001, 0.1, 0.01, 1, 10, 100]}

In [67]:
grid_search = GridSearchCV(estimator=lasso, param_grid=param_grid, cv = 5, scoring= 'r2', verbose=2)

In [68]:
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.1, 0.01, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [69]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.1, 0.01, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [75]:
grid_search.best_params_['alpha']

0.1

In [71]:
grid_search.best_score_

np.float64(0.7964209726696481)

In [72]:
grid_search.best_estimator_

Lasso(alpha=0.1)

In [74]:
y_pred  = grid_search.best_estimator_.predict(x_test)

In [76]:
r2_score(y_test,y_pred)

0.8345318641232303

In [77]:
#randomaize Searcg CV for lasso

In [78]:
lasso = Lasso()

In [85]:
param_distribution = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}
random_search_lasso = RandomizedSearchCV(estimator=lasso, param_distributions=param_distribution,n_iter=3, cv = 5, scoring='r2', verbose=2)

In [86]:
random_search_lasso

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [88]:
random_search_lasso.fit(x_train,y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 1, 10,
                                                  100]},
                   scoring='r2', verbose=2)

In [89]:
random_search_lasso.best_score_

np.float64(0.7944410612391779)

In [90]:
y_pred  = random_search_lasso.predict(x_test)

In [91]:
r2_score(y_test,y_pred)

0.8348812953883181

In [100]:
#Ridge Grid Search Cv
ridge = Ridge()
param_grid = {'alpha': [0.001, 0.1, 0.01, 1,10, 100]}
ridge = GridSearchCV(estimator=ridge, param_grid=param_grid, cv = 5,scoring='r2', verbose=2)
ridge.fit(x_train,y_train)
print(ridge.best_params_['alpha'])
print(ridge.best_estimator_)
y_pred = ridge.best_estimator_.predict(x_test)
print(r2_score(y_test,y_pred))

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
10
Ridge(alpha=10)
0.8354145247502055

In [101]:
#Randomized Search Cv


ridge = Ridge()
param_distributions = {'alpha': [0.001, 0.1, 0.01, 1,10, 100]}
ridge = RandomizedSearchCV(estimator=ridge, param_distributions=param_distributions,n_iter=3, cv = 5,scoring='r2', verbose=2)
ridge.fit(x_train,y_train)
print(ridge.best_params_['alpha'])
print(ridge.best_estimator_)
y_pred = ridge.best_estimator_.predict(x_test)
print(r2_score(y_test,y_pred))

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
10
Ridge(alpha=10)
0.8354145247502055

In [ ]:
#Elastic net gridsearch CV
model = ElasticNet()
param_grid = {'alpha': [0.001, 0.1, 0.01, 1,10, 100],
              'l1_ratio': [0.1,0.4,0.9]}
model = GridSearchCV(estimator=model, param_grid=param_grid, cv = 5,scoring='r2', verbose=2)
model.fit(x_train,y_train)
print(model.best_params_['alpha'])
print(model.best_estimator_)
y_pred = model.best_estimator_.predict(x_test)
print(r2_score(y_test,y_pred))

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
0.1
ElasticNet(alpha=0.1, l1_ratio=0.9)
0.8345726087080976

In [104]:
#Elastic net Randomized Search CV
model = ElasticNet()
param_distributions = {'alpha': [0.001, 0.1, 0.01, 1,10, 100],
              'l1_ratio': [0.1,0.4,0.9]}
model = RandomizedSearchCV(estimator=model, param_distributions=param_distributions,n_iter=3, cv = 5,scoring='r2', verbose=2)
model.fit(x_train,y_train)
print(model.best_params_['alpha'])
print(model.best_estimator_)
y_pred = model.best_estimator_.predict(x_test)
print(r2_score(y_test,y_pred))

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
0.1
ElasticNet(alpha=0.1, l1_ratio=0.4)
0.835267991940889